#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

group=de.fraunhofer.iee
version=1.0.0-edc0.14.0

# information required for publishing artifacts:
edcScmConnection=scm:git@github.com:Re4DE/identity-hub.git
edcScmUrl=https://github.com/Re4DE/identity-hub.git
