[metadata]
format.version = "1.1"

[versions]
edc = "0.14.0"
edc-build = "1.1.1"
shadow = "8.3.6"

[libraries]
# edc libs
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }

# ih libs
edc-ih-credentials-spi = { module = "org.eclipse.edc:verifiable-credential-spi", version.ref = "edc" }
edc-ih-spi = { module = "org.eclipse.edc:identity-hub-spi", version.ref = "edc" }

# BOM Modules
bom-ih = { module = "org.eclipse.edc:identityhub-bom", version.ref = "edc" }
bom-ih-feat-sql = { module = "org.eclipse.edc:identityhub-feature-sql-bom", version.ref = "edc" }

[bundles]
ih = ["bom-ih", "bom-ih-feat-sql", "edc-vault-hashicorp"]

[plugins]
edc-build = { id = "org.eclipse.edc.edc-build", version.ref = "edc-build" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
