#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

edc.participant.id=did:web:localhost%3A10085:tester
edc.component.id=identityhub
edc.hostname=localhost

edc.iam.did.web.use.https=false

edc.ih.api.superuser.key=c3VwZXItdXNlcg==.devpass

web.http.path=/api
web.http.port=10080
web.http.credentials.path=/api/credentials
web.http.credentials.port=10081
web.http.identity.path=/api/identity
web.http.identity.port=10082
web.http.sts.path=/api/sts
web.http.sts.port=10083
web.http.version.path=/api/version
web.http.version.port=10084
web.http.did.path=/
web.http.did.port=10085

edc.vault.hashicorp.url=http://localhost:8200
edc.vault.hashicorp.token=devpass

edc.sql.schema.autocreate=true
edc.datasource.default.user=edc
edc.datasource.default.password=devpass
edc.datasource.default.url=jdbc:postgresql://localhost:5432/edc
